baseURL = "https://vesey.tech/"
languageCode = "en-us"
title = "vesey.tech"
theme = "minimal"
googleAnalytics = ""
staticDir = ["static"]

pygmentsUseClasses = true
pygmentsCodefences = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

[params]
  author = "Will Vesey"
#  profilePic = "me.png"
  description = "Welcome to my slice of Internet"
  githubUsername = "#"
  accent = "#77448b"
  showBorder = true
  backgroundColor = "white"
  font = "Raleway" # should match the name on Google Fonts!
  highlight = true
  highlightStyle = "default"
  highlightLanguages = ["python", "go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/about/"
  name = "About"
  weight = 2

[[menu.main]]
  url = "/post/"
  name = "Posts"
  weight = 3

[[menu.main]]
  url = "/project/"
  name = "Projects"
  weight = 4

[[menu.main]]
  url = "/space/"
  name = "Space"
  weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
  url = "mailto:will@vesey.tech"
  name = "envelope-o"
  weight = 1

[[menu.icon]]
  url = "https://github.com/1ttric/"
  name = "github"
  weight = 2

[[menu.icon]]
  url = "https://www.linkedin.com/in/william-vesey-312359135/"
  name = "linkedin"
  weight = 3

