baseURL = "https://vesey.tech/"
languageCode = "en-us"
title = "vesey.tech"
theme = "vtec"
publishDir = "docs"

[markup]
[markup.highlight]
#noClasses = false
style = "algol"
[markup.goldmark.renderer]
unsafe = true
